import { BillingProvider, BillingProviderError, EnrollmentInput, ProviderAuthorizedPayment, ProviderPlan, ProviderSubscription } from "./billing-provider";
type Json = Record<string, unknown>; const API = "https://api.mercadopago.com";
const str = (v: unknown) => typeof v === "string" ? v : null; const num = (v: unknown) => typeof v === "number" && Number.isFinite(v) ? v : null; const date = (v: unknown) => { const x = str(v); if (!x) return null; const d = new Date(x); return Number.isNaN(d.getTime()) ? null : d; };
export class MercadoPagoBillingProvider implements BillingProvider {
  readonly name = "mercado_pago" as const;
  constructor(private readonly token: string, private readonly timeoutMs = 8_000) {}
  private async request(path: string, init: RequestInit) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), this.timeoutMs); timer.unref(); try { const response = await fetch(`${API}${path}`, { ...init, signal: controller.signal, headers: { Authorization: `Bearer ${this.token}`, "Content-Type": "application/json", ...(init.headers || {}) } }); const body = await response.json().catch(() => null) as Json | null; if (!response.ok) throw new BillingProviderError(`Mercado Pago respondió ${response.status}.`, response.status === 404 ? "not_found" : response.status === 429 ? "rate_limited" : "upstream"); if (!body) throw new BillingProviderError("Mercado Pago devolvió una respuesta inválida.", "malformed"); return body; } catch (error) { if (error instanceof BillingProviderError) throw error; if (error instanceof Error && error.name === "AbortError") throw new BillingProviderError("Mercado Pago excedió el tiempo de espera.", "timeout"); throw new BillingProviderError("No se pudo contactar Mercado Pago.", "upstream"); } finally { clearTimeout(timer); } }
  private plan(body: Json): ProviderPlan { const recurring = body.auto_recurring as Json | undefined; const id = str(body.id); const amount = num(recurring?.transaction_amount); const currency = str(recurring?.currency_id); if (!id || amount === null || !currency) throw new BillingProviderError("Plan de Mercado Pago inválido.", "malformed"); return { id, status: str(body.status) ?? "unknown", amount, currency, frequency: 1, frequencyType: "months" }; }
  private subscription(body: Json): ProviderSubscription { const recurring = body.auto_recurring as Json | undefined; const id = str(body.id); if (!id) throw new BillingProviderError("Suscripción de Mercado Pago inválida.", "malformed"); return { id, planId: str(body.preapproval_plan_id), externalReference: str(body.external_reference), status: str(body.status) ?? "unknown", version: num(body.version), lastModifiedAt: date(body.last_modified), currentPeriodStart: date(recurring?.start_date), currentPeriodEnd: date(recurring?.end_date), nextBillingDate: date(body.next_payment_date), initPoint: str(body.init_point) }; }
  async ensurePlan(input: { existingPlanId?: string | null; amount: number; currency: string; reason: string }) { if (input.existingPlanId) return this.getPlan(input.existingPlanId); return this.plan(await this.request("/preapproval_plan", { method: "POST", body: JSON.stringify({ reason: input.reason, auto_recurring: { frequency: 1, frequency_type: "months", transaction_amount: input.amount, currency_id: input.currency } }) })); }
  async getPlan(id: string) { return this.plan(await this.request(`/preapproval_plan/${encodeURIComponent(id)}`, { method: "GET" })); }
  async updatePlan(id: string, input: { amount: number; reason?: string }) { return this.plan(await this.request(`/preapproval_plan/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify({ ...(input.reason ? { reason: input.reason } : {}), auto_recurring: { frequency: 1, frequency_type: "months", transaction_amount: input.amount } }) })); }
  async createEnrollment(input: EnrollmentInput) { return this.subscription(await this.request("/preapproval", { method: "POST", body: JSON.stringify({ preapproval_plan_id: input.planId, external_reference: input.externalReference, payer_email: input.payerEmail, card_token_id: input.cardToken, back_url: input.backUrl, status: "authorized", auto_recurring: { frequency: 1, frequency_type: "months", transaction_amount: input.amount, currency_id: input.currency } }) })); }
  async getSubscription(id: string) { return this.subscription(await this.request(`/preapproval/${encodeURIComponent(id)}`, { method: "GET" })); }
  async cancelSubscription(id: string) { return this.subscription(await this.request(`/preapproval/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify({ status: "cancelled" }) })); }
  async getAuthorizedPayment(id: string) { const body = await this.request(`/authorized_payments/${encodeURIComponent(id)}`, { method: "GET" }); const value = str(body.id); if (!value) throw new BillingProviderError("Pago autorizado inválido.", "malformed"); return { id: value, subscriptionId: str(body.preapproval_id) ?? "", status: str(body.status) ?? "unknown", amount: num(body.transaction_amount) ?? 0, currency: str(body.currency_id) ?? "ARS", paidAt: date(body.date_created), periodStart: date(body.date_created), periodEnd: date(body.date_last_updated) }; }
  async listAuthorizedPayments(_subscriptionId: string): Promise<ProviderAuthorizedPayment[]> { return []; }
}
