ALTER TABLE `Promotion`
  ADD COLUMN `maxRedemptions` INTEGER NULL;

ALTER TABLE `AppNotification`
  MODIFY `type` ENUM(
    'REDEMPTION_VALIDATED',
    'REDEMPTION_CREATED',
    'COMMERCE_APPROVED',
    'COMMERCE_REJECTED',
    'COMMERCE_PENDING'
  ) NOT NULL;
