ALTER TABLE `User`
  ADD COLUMN `sessionVersion` INTEGER NOT NULL DEFAULT 0;

ALTER TABLE `Session`
  ADD COLUMN `lastUsedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `Redemption`
  ADD COLUMN `validationBlockedUntil` DATETIME(3) NULL;
